theme: jekyll-theme-minimal

R:
  type: programming
  color: "#198CE7"
  aliases:
  - R
  - Rscript
  - splus
  extensions:
  - ".r"
  - ".rd"
  - ".rsx"
  filenames:
  - ".Rprofile"
  - expr-dist
  interpreters:
  - Rscript
  tm_scope: source.r
  ace_mode: r
  codemirror_mode: r
  codemirror_mime_type: text/x-rsrc
  language_id: 307
